/** Stable error codes returned by the API (`{ error: { code, message } }`). Clients map these to localised text. */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_RESEND_TOO_SOON: 'OTP_RESEND_TOO_SOON',
  OTP_DELIVERY_FAILED: 'OTP_DELIVERY_FAILED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ROLE_NOT_ACTIVE: 'ROLE_NOT_ACTIVE',
  TOTP_REQUIRED: 'TOTP_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  REGISTRATION_LOCKED: 'REGISTRATION_LOCKED',
  REGISTRATION_INCOMPLETE: 'REGISTRATION_INCOMPLETE',
  VEHICLE_ALREADY_REGISTERED: 'VEHICLE_ALREADY_REGISTERED',
  UPLOAD_INVALID: 'UPLOAD_INVALID',
  INVALID_STATE: 'INVALID_STATE',
  OUT_OF_SERVICE_AREA: 'OUT_OF_SERVICE_AREA',
  MAPS_UNAVAILABLE: 'MAPS_UNAVAILABLE',
  QUOTE_UNAVAILABLE: 'QUOTE_UNAVAILABLE',
  INTERNAL: 'INTERNAL',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorBody {
  error: { code: ErrorCode; message: string; details?: unknown };
}
